// <auto-generated />
using System;
using DJ.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DJ.Infrastructure.Migrations
{
    [DbContext(typeof(DjDbContext))]
    partial class DjDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.2");

            modelBuilder.Entity("DJ.Domain.Entities.Member", b =>
                {
                    b.Property<ulong>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<ulong>("GuildId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Members");
                });

            modelBuilder.Entity("DJ.Domain.Entities.Member", b =>
                {
                    b.OwnsMany("DJ.Domain.Entities.PlayedTrack", "PlayedTracks", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("TEXT");

                            b1.Property<string>("Album")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.Property<string>("Artists")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.Property<DateTimeOffset>("CreatedAt")
                                .HasColumnType("TEXT");

                            b1.Property<string>("Genres")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.Property<ulong>("MemberId")
                                .HasColumnType("INTEGER");

                            b1.Property<int>("Score")
                                .HasColumnType("INTEGER");

                            b1.Property<string>("Title")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.Property<string>("TrackId")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.Property<string>("Uri")
                                .HasColumnType("TEXT");

                            b1.HasKey("Id");

                            b1.HasIndex("MemberId");

                            b1.ToTable("PlayedTracks", (string)null);

                            b1.WithOwner("Member")
                                .HasForeignKey("MemberId");

                            b1.Navigation("Member");
                        });

                    b.Navigation("PlayedTracks");
                });
#pragma warning restore 612, 618
        }
    }
}
